import { Geist, Geist_Mono } from "next/font/google";
import { Figtree, Martel, Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  weight: ["400", "500", "600", "700"],
});

const martel = Martel({
  subsets: ["latin"],
  variable: "--font-martel",
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${martel.variable} ${inter.variable}`}
    >
      <body
        className="font-sans"
        style={{
          margin: 0,
          padding: 0,

          boxSizing: "border-box",
        }}
      >
        {/* Header */}
        <Header />

        {/* Main content */}
        <main style={{ flex: 1 }}>{children}</main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
